import LegalPageLayout from "@/components/LegalPageLayout";
import { Link } from "react-router-dom";

const TermsOfService = () => (
  <LegalPageLayout>
    <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
    <p className="text-muted-foreground mb-8 text-sm">Last updated: April 1, 2026</p>

    <div className="prose prose-sm dark:prose-invert max-w-none space-y-6 text-foreground/90">
      <section>
        <h2 className="text-xl font-semibold mb-2">1. Acceptance of Terms</h2>
        <p className="text-muted-foreground">
          By accessing or using FaceNova ("the Service"), you agree to be bound by these Terms of Service.
          If you do not agree, you may not use the Service. You must be at least 16 years old to use FaceNova.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">2. Description of Service</h2>
        <p className="text-muted-foreground">
          FaceNova is an AI-powered beauty and facial analysis platform that provides glow scores,
          symmetry analysis, skin analysis, hairstyle recommendations, and style improvement suggestions.
          Results are generated by artificial intelligence and are for entertainment and informational
          purposes only — they do not constitute medical, dermatological, or professional advice.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">3. User Accounts</h2>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
          <li>You are responsible for maintaining the security of your account credentials.</li>
          <li>You must provide accurate information during registration.</li>
          <li>You may not create accounts for others or share account access.</li>
          <li>We reserve the right to suspend accounts that violate these terms.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">4. Photo Upload & Content</h2>
        <p className="text-muted-foreground">By uploading photos to FaceNova, you:</p>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
          <li>Confirm that you have the right to upload the photo (it is of yourself or you have consent).</li>
          <li>Grant us a limited license to process the photo for analysis purposes only.</li>
          <li>Understand that uploading photos of others without their consent is prohibited.</li>
          <li>Acknowledge that you may not upload inappropriate, offensive, or illegal content.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">5. AI Analysis Disclaimer</h2>
        <p className="text-muted-foreground">
          Our AI analysis provides scores and recommendations based on algorithmic processing. These results:
        </p>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
          <li>Are not medical or professional assessments.</li>
          <li>May vary based on photo quality, lighting, and angle.</li>
          <li>Should not be used as the sole basis for medical or cosmetic decisions.</li>
          <li>Are provided "as is" without guarantees of accuracy.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">6. Plans & Payments</h2>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
          <li>Free tier users have limited access to features and analysis count.</li>
          <li>Premium plans are billed on a recurring basis as described at time of purchase.</li>
          <li>You may cancel your subscription at any time; access continues until the end of the billing period.</li>
          <li>Refunds are handled on a case-by-case basis. Contact support for refund requests.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">7. Product Recommendations</h2>
        <p className="text-muted-foreground">
          FaceNova may recommend third-party beauty and skincare products. Some recommendations may contain
          affiliate links. We are not responsible for the quality, safety, or effectiveness of third-party products.
          Always consult a dermatologist before trying new skincare products.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">8. Prohibited Use</h2>
        <p className="text-muted-foreground">You may not:</p>
        <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
          <li>Use the Service for harassment, bullying, or to demean others.</li>
          <li>Attempt to reverse-engineer our AI models or algorithms.</li>
          <li>Scrape, bot, or automate interactions with the Service.</li>
          <li>Upload photos of minors.</li>
          <li>Use the Service for any illegal purpose.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">9. Intellectual Property</h2>
        <p className="text-muted-foreground">
          All content, branding, AI models, and technology on FaceNova are owned by us or our licensors.
          You may not copy, reproduce, or distribute any part of the Service without written permission.
          Your uploaded photos remain your property.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">10. Limitation of Liability</h2>
        <p className="text-muted-foreground">
          FaceNova is provided "as is" without warranties of any kind. We are not liable for any damages
          arising from your use of the Service, including but not limited to decisions made based on
          AI analysis results. Our total liability shall not exceed the amount you paid for the Service
          in the 12 months preceding the claim.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">11. Termination</h2>
        <p className="text-muted-foreground">
          We may terminate or suspend your access at any time for violation of these terms.
          You may delete your account at any time. Upon termination, your data will be deleted
          in accordance with our <Link to="/privacy" className="text-primary underline">Privacy Policy</Link>.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">12. Changes to Terms</h2>
        <p className="text-muted-foreground">
          We may modify these terms at any time. Continued use after changes constitutes acceptance.
          We will notify users of material changes via email or in-app notification.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold mb-2">13. Contact</h2>
        <p className="text-muted-foreground">
          Questions about these terms? Visit our{" "}
          <Link to="/support" className="text-primary underline">support page</Link>.
        </p>
      </section>
    </div>
  </LegalPageLayout>
);

export default TermsOfService;
